[package]
name = "pluto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
tracing = "0"
tracing-subscriber = "0"
config = "0"
dotenv = "0"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.axum]
version = "0"
features = ["tracing"]

[dependencies.tower-http]
version = "0"
features = ["trace"]

[dependencies.sqlx]
version = "0"
features = ["postgres"]
