[package]
name = "pluto"
version = "0.3.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0", features = ["runtime-tokio", "postgres", "sqlite"] }
async-trait = "0"
axum = "0"
tower = "0"
axum-extra = "0"
serde = { version = "1", features = ["derive"] }
dotenv = "0"
config = "0"
tracing = "0"
tracing-subscriber = "0"
