[package]
name = "pluto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
tracing = "0"
tracing-subscriber = "0"
config = "0"
dotenv = "0"
rust-embed = "8"
mime_guess = "2"
nanoid = "0"
argon2 = "0"
askama = "0"
minify-html-onepass = "0"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.axum]
version = "0"
features = ["tracing"]

[dependencies.axum-extra]
version = "0"
features = ["typed-header"]

[dependencies.tower]
version = "0"
features = ["util"]

[dependencies.tower-http]
version = "0"
features = ["fs", "trace", "compression-gzip", "compression-deflate", "compression-zstd", "compression-br"]

[dependencies.sqlx]
version = "0"
features = ["postgres", "runtime-tokio"]

