[package]
name = "pluto"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
strip = true        # Strip symbols from binary*

[dependencies]
argon2 = "0"
askama = "0"
config = "0"
dotenv = "0"
mime_guess = "2"
minify-html-onepass = "0"
nanoid = "0"
rand = "0"
regex = "1"
rust-embed = "8"
serde_json = "1"
tracing = "0"
tracing-subscriber = "0"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.axum]
version = "0"
features = ["tracing"]

[dependencies.axum-extra]
version = "0"
features = ["typed-header", "cookie", "cookie-private"]

[dependencies.tower]
version = "0"
features = ["util"]

[dependencies.tower-http]
version = "0"
features = ["fs", "trace", "compression-gzip", "compression-deflate", "compression-zstd", "compression-br"]

[dependencies.sqlx]
version = "0"
features = ["postgres", "runtime-tokio", "chrono"]

[dependencies.chrono]
version = "0"
features = ["serde"]

[dependencies.chrono-tz]
version = "0"
features = ["case-insensitive", "serde"]
