[package]
name = "pluto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
tracing = "0"
tracing-subscriber = "0"
config = "0"
dotenv = "0"
rust-embed = "8"
mime_guess = "2"
askama_axum = "0"
nanoid = "0"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.axum]
version = "0"
features = ["tracing"]

[dependencies.axum-extra]
version = "0"
features = []

[dependencies.tower]
version = "0"
features = ["util"]

[dependencies.tower-http]
version = "0"
features = ["fs", "trace"]

[dependencies.sqlx]
version = "0"
features = ["postgres", "runtime-tokio"]

[dependencies.askama]
version = "0"
features = ["with-axum"]
